### ISSUE TITLE
Svelte: does clicking on flow should update nodes?

### ISSUE THREAD

**Issue by 1bye** [xyflow/xyflow#3638]
### Describe the Bug

Hey,

Not sure if this is a bug, but when I click on the SvelteFlow component, it updates the node store. Check out the video for a quick demo:

[Video](https://drive.google.com/file/d/1OVgVe2PvRjqAhs8qsZ7al4xbM5EtijCF/view?usp=sharing)

Is this expected behavior or possibly a bug?

Thanks!

### Steps to Reproduce the Bug or Issue

Link to repro:
[https://stackblitz.com/edit/ivtn2m?file=src%2Fexample%2FApp.svelte](Stackblitz)

### Expected behavior

The clicking on svelte flow shouldn't update the nodes

### Screenshots or Videos

[Video](https://drive.google.com/file/d/1OVgVe2PvRjqAhs8qsZ7al4xbM5EtijCF/view?usp=sharing)

### Platform

- OS: [Ubuntu]
- Browser: [Chrome]
- Version: [119]

**Comment by moklick** [comment]
fixed in 0.0.28

**Comment by 1bye** [comment]
Hmm, in my use case isn't work. When I updated to 0.0.28 in main project, the issue isn't solved + in stackblitz the same, look:
[Video](https://drive.google.com/file/d/1_hBEcDrn1httHFva_h9FEZ7K4PGVASap/view?usp=sharing)

**Comment by moklick** [comment]
arg :/ you are right. Will be fixed with the next release.

**Comment by moklick** [comment]
finally fixed in 0.0.29 https://svelteflow.dev/whats-new/2023-12-13
