### ISSUE TITLE
Flickering / z-fighting / re-rendering between canvas & nodes on click/drag, introduced in 11.10.4

### ISSUE THREAD

**Issue by IanLondon** [xyflow/xyflow#4159]
### Describe the Bug

When I upgraded react-flow in my project, I encountered a bug where dragging a node "flickers" between selecting the canvas versus selecting the node: 
- while a node is being dragged, the mouse cursor image flickers between pointer and drag
- when attempting to drag a node, about half the time dragging a node will drag the canvas instead, so it take multiple attempts to drag a node
- similarly, it may take a few clicks to select a node because it seems to click "through" the node to the canvas half the time.
 
It feels like z-fighting: the node and the canvas seem to be competing for who is the target of the cursor. Though it's probably re-rendering during the mousedown on click and during the mousemove on drag.

I am using a custom node, I'm not sure what is relevant to include about it.

Versions I tested: does it have this flickering bug? These are the versions I tested in an attempt to narrow it down:

- 11.11.1 yes
- 11.10.4 yes! this is the breaking change
- 11.10.3 no
- 11.10.2 no
- 11.10.0 no
- 11.9.4 no
- 11.8.3 no

I'm guessing this may have been introduced by #3897 just from context clues?? Maybe the [changes to useEffect](https://github.com/xyflow/xyflow/pull/3897/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&file-filters%5B%5D=.yaml&show-viewed-files=true#diff-474ae29b08bd432d76c99d441f44bddc3d45ef51e3be7426966eaa101cb8094fR146) are causing a re-render?

### Steps to Reproduce the Bug or Issue

1. Use version 11.10.4+
2. Click to drag a custom node (All the custom nodes I've tried have this flickering behavior in 11.10.4+, they don't have any unusual parts: no input fields, etc, so I'm not sure what to note about the nodes I tested)
3. About half the time, the node will not be selected, and the canvas will be grabbed instead. When the node is grabbed, the cursor will flicker between grab and pointer icons

Downgrading to 11.10.3 fixes the issue.

### Expected behavior

As a user, I expected the normal drag-and-drop behavior for nodes.

### Platform

- OS: Linux
- Browser: Chrome
- Version: 11.10.4+

**Comment by moklick** [comment]
Does this issue happen with any of the examples on the website?

**Comment by ifedyukin** [comment]
It looks like the flickering is caused by changing the `visibility` property, probably in this [line](https://github.com/xyflow/xyflow/blob/467223b9a321f6af4555244de0990ea2b766cd0c/packages/react/src/components/NodeWrapper/index.tsx#L186).

I've tried to create reproducable demo:
- [CodeSandbox 11.11.1](https://codesandbox.io/p/sandbox/react-flow-11-11-1-8dt7lw?file=%2FApp.js%3A21%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwtcnr7r00073b6kbwsscomf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwtcnr7r00033b6kmxugtmzg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwtcnr7r00043b6k03ktvuqg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwtcnr7r00063b6kmkv23h0k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.93467505160762%252C53.06532494839238%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwtcnr7r00033b6kmxugtmzg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwtcnr7r00023b6kr6veubc9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A19%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwtcnr7r00033b6kmxugtmzg%2522%252C%2522activeTabId%2522%253A%2522clwtcnr7r00023b6kr6veubc9%2522%257D%252C%2522clwtcnr7r00063b6kmkv23h0k%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwtcnr7r00053b6kmh5cdmuz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwtcnr7r00063b6kmkv23h0k%2522%252C%2522activeTabId%2522%253A%2522clwtcnr7r00053b6kmh5cdmuz%2522%257D%252C%2522clwtcnr7r00043b6k03ktvuqg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwtcnr7r00043b6k03ktvuqg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D);
- [CodeSandbox 11.10.1](https://codesandbox.io/p/sandbox/react-flow-11-10-3-k3k9x5?file=%2FApp.js%3A82%2C15&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwtcnr7r00073b6kbwsscomf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwtcnr7r00033b6kmxugtmzg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwtcnr7r00043b6k03ktvuqg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwtcnr7r00063b6kmkv23h0k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwtcnr7r00033b6kmxugtmzg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwtcnr7r00023b6kr6veubc9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A82%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A82%252C%2522endColumn%2522%253A15%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwtcnr7r00033b6kmxugtmzg%2522%252C%2522activeTabId%2522%253A%2522clwtcnr7r00023b6kr6veubc9%2522%257D%252C%2522clwtcnr7r00063b6kmkv23h0k%2522%253A%257B%2522id%2522%253A%2522clwtcnr7r00063b6kmkv23h0k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwtcnr7r00053b6kmh5cdmuz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwtcnr7r00053b6kmh5cdmuz%2522%257D%252C%2522clwtcnr7r00043b6k03ktvuqg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwtcnr7r00043b6k03ktvuqg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

This probably happens when we reinit nodes due to an external update, e.g. a backend response.
I tried to simulate this situation in the sandbox. But it's not always reproducible.

Also, attached 2 videos:
https://github.com/xyflow/xyflow/assets/11480414/b04673f2-24f8-4860-b766-3a31a858cf1c - 11.11.1
https://github.com/xyflow/xyflow/assets/11480414/93a68828-6c89-473e-b4f9-41e20eb88ac3 - 11.10.1

**Comment by peterkogo** [comment]
@IanLondon Have you by any chance updated to v12 yet? This should be fixed in the new versions.

**Comment by EzraBrooks** [comment]
Hi, I tried upgrading to v12 (quickly and dirtily) and it still has a similar issue.

**Comment by moklick** [comment]
I guess the issue here is that you are creating new nodes. This would not happen if you would iterate over your existing nodes and not throw away any information. Same for v12. If you want to update your nodes, you need to keep `node.measured`. Otherwise we need to re-initialize them. 

@IanLondon could you provide an example for this?

**Comment by EzraBrooks** [comment]
> This would not happen if you would iterate over your existing nodes and not throw away any information.

Hmm, I've invested quite a bit of work in my application to avoid this case, but it's possible there's still some edge cases where it's happening. Happy to refer to an example of reinitialization and see if it helps, once that example exists.

**Comment by peterkogo** [comment]
Just to clarify. Things like this usually appear when you are using `setNodes` and ignoring the previous nodes that get supplied.

```javascript
// Good
setNodes(nodes => nodes.map(node => { ...node, /* changes here */ }));

// Bad
setNodes(someNodesIHaveCachedAndModified);
```

Can you make sure this is not happening?

**Comment by EzraBrooks** [comment]
Fairly certain. Also, I can confirm this still happens in 11.11.4, which dependabot updated me to, thus breaking my application.

If that situation is inadvisable, it seems like the application should log a warning when it happens?

I'm pretty frustrated that I pay for a pro subscription and this neither works nor tells me that I'm doing something wrong and shooting myself in the foot.. since it worked fine before 11.10.4.

**Comment by moklick** [comment]
Please re-open if the issue is not fixed in the latest version (12.x.x)

**Comment by sachinD2205** [comment]
Yeah, that Filker issue is still there

**Comment by peterkogo** [comment]
If anyone can provide a reproduction for this, I'd be happy to fix it. You can create a fork of our [codesandbox template](https://new.reactflow.dev/ts) and show us how the flickering occurs.

**Comment by sachinD2205** [comment]
I am using    "reactflow": "^11.11.0", here you used  "@xyflow/react": "12.6.1", is this different?

**Comment by peterkogo** [comment]
We renamed the library for the newest version

**Comment by sachinD2205** [comment]
This filker issue was fixed or not in the latest version. Do you have any solution for the filker issue for this version "reactflow": "^11.11.0"? If so, it will be very helpful for us.   Thanks for the quick reply

**Comment by peterkogo** [comment]
Unfortunately we do not support that version any longer. Many architectural changes were required to prevent things like the flickering issue you are experiencing.

**Comment by asparagusbeef** [comment]
I am still getting this flicker, using "@xyflow/react": "12.8.4".

**Comment by peterkogo** [comment]
@asparagusbeef Please create a new issue with a full reproduction of this issue. I really can't replicate any of this on my end.
