### ISSUE TITLE
Pinch zoom on "nowheel" elements causes the entire page to zoom

### ISSUE THREAD

**Issue by wfortin** [xyflow/xyflow#5074]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.4.2
- Browser and version: 133.0.6943.127
- OS and version: MacOS 15.1.1 (24B91)

https://codesandbox.io/p/sandbox/react-flow-starter-ts-r69228

### Live code example

https://codesandbox.io/p/sandbox/react-flow-starter-ts-r69228

### Describe the Bug

Sample (simply added classname "nowheel" on PositionLoggerNode)

Pinch zoom on a "nowheel" element causes the entire viewport to zoom.

### Steps to reproduce the bug or issue

To repro:
1. Pinch zoom with trackpad on the canvas, zooms in/out as expected.
2. Pinch zoom with trackpad on any node, the entire viewport zooms. I'd expect it to either do nothing OR to still zoom.

### Expected behavior

I'd expect it to either do nothing OR to still zoom.

**Comment by wfortin** [comment]
I ended up with this as a workaround:

Hopefully this could be baked into the "nowheel" handler, and even better it would still zoom if `zoomOnPinch` is enabled.

```ts
/**
 * Pinch zoom on 'nowheel' nodes ends up zooming the entire viewport.
 * This is a workaround to prevent this.
 */
const preventPinchZoom = (e: WheelEvent) => {
  if (e.ctrlKey) {
    e.preventDefault();
  }
};

useEffect(() => {
  document.addEventListener('wheel', preventPinchZoom, {
    passive: false,
  });

  return () => document.removeEventListener('wheel', preventPinchZoom);
}, []);
```

**Comment by TrySpace** [comment]
Does this still work if you wrap the function in useCallback?

**Comment by moklick** [comment]
Thanks @wfortin we will have a look.

**Comment by moklick** [comment]
This is fixed in 12.5.4

**Comment by andreasvirkus** [comment]
I still experience this issue with `12.8.4` on MacOS, Sequoia 15.5, Brave `1.81.136 Chromium: 139.0.7258.143 (Official Build) (arm64)` (pinching on trackpad)
